name: Update Docker Hub Description

on:
  push:
    branches:
      - "main"
    paths:
      - "README.md"
      - ".github/workflows/dockerhub-description.yml"

jobs:
  update-desc:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Run peter-evans/dockerhub-description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
